In [2]:
# checking shape of numpy arrays
import numpy as np
n1 = np.array([[1,2,3],[4,5,6]])
n1

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
n1.shape

(2, 3)

In [4]:
n1.shape = (3,2)
n1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [5]:
import numpy as np
n2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
n2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [6]:
n2.shape

(2, 5)

In [7]:
n2.shape = (5,2)
n2

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])